WITH INVOICE AS (
    SELECT 
        LINE_ITEM_ID,
        SERVICE_DESCRIPTION,
   FROM INVOICE_LINE_ITEMS
),
SER_CAT AS (
    SELECT 
        ARRAY_AGG(CATEGORY_NAME) AS CAT 
    FROM SERVICE_CATEGORIES
),
FINAL AS (
    SELECT 
        I.LINE_ITEM_ID,
        I.SERVICE_DESCRIPTION AS INPUT,
        CAT AS CLASSES,
        SNOWFLAKE.CORTEX.CLASSIFY_TEXT(INPUT, CLASSES):"label" AS PRODUCT_CATEGORY
    FROM INVOICE AS I,
        SER_CAT AS S
)
SELECT 
    LINE_ITEM_ID, 
    INPUT,
    CLASSES, 
    PRODUCT_CATEGORY
FROM FINAL;
